### ISSUE TITLE
Reihenfolge im Foliensatz ändern, Folien 6 und 7 tauschen

### ISSUE THREAD

**Issue by pa-ru** [aawada78/angular-workshop#1]
Vorschlag: Zuerst erklären was eine SPA ist und warum wir die wollen und dann den Schwenk auf Angular machen, das zufälligerweise ideal für SPA ist.

Auf der Angular-Intro Folie steht auch SPA, das ist zu diesem Zeitpunkt aber evtl. nicht allen ein Begriff.

**Comment by aawada78** [comment]
Klingt gut. Machst du das? Ich gehe gerade den Code durch.

**Comment by pa-ru** [comment]
ich probiers... hab allerding kein Office auf der Kiste... ich probiers mal online ;-)

**Comment by aawada78** [comment]
Online wird es schwierig, da es nicht auf Onedrive liegt. Ich mach das und bringe gleich die Änderungen von Issue #2 mit rein.

**Comment by pa-ru** [comment]
klappt aber gut...
Bin drüber.

**Comment by aawada78** [comment]
Ok, super 👍
